name: Comment Test

on:
  issue_comment:
    types: [created]

jobs:
  log:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - run: |
          echo "ğŸ’¬ Comment detected on PR"
