name: QA Review Trigger

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string
  # pull_request:
  #   types: [ opened, labeled, unlabeled, synchronize, reopened ]
  # pull_request_review:
  #   types: [submitted, dismissed]

concurrency:
  group: qa-review-trigger-${{ inputs.pr_number }}
  cancel-in-progress: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Re-run QA Approval
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "üîÅ Triggering QA Approval Check workflow..."
          gh workflow run ".github/workflows/qa-approval.yml" \
            -R ${{ github.repository }} \
            --ref "${{ github.event.pull_request.head.ref }}" \
            -f pr_number=${{ github.event.pull_request.number }}